# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'waither' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'VerticalSlider'
  pod 'CircularSlider'
  pod 'SnapKit'


  # Pods for waither

  pod 'KakaoSDKCommon'
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKUser'

end
